#+TITLE: GNU Emacs manual - 5 Keys and Commands
#+AUTHOR: Free Software Foundation, Inc.
#+DATE: <2023-09-25 Mon>

* 6 Entering Emacs

The usual way to invoke Emacs is with the shell command emacs. From a terminal window running a Unix shell on a GUI terminal, you can run Emacs in the background with emacs &; this way, Emacs won’t tie up the terminal window, so you can use it to run other shell commands. (For comparable methods of starting Emacs on MS-Windows, see How to Start Emacs on MS-Windows.)

呼叫 Emacs 的常用方法是使用 shell 命令 emacs。從在 GUI 終端機上執行 Unix shell 的終端機視窗中，您可以使用 ; 在背景執行 Emacs emacs &。這樣，Emacs 就不會佔用終端窗口，因此您可以使用它來執行其他 shell 命令。（有關在 MS-Windows 上啟動 Emacs 的類似方法，請參閱如何在 MS-Windows 上啟動 Emacs。）

When Emacs starts up, the initial frame displays a special buffer named ‘*GNU Emacs*’. This startup screen contains information about Emacs and links to common tasks that are useful for beginning users. For instance, activating the ‘Emacs Tutorial’ link opens the Emacs tutorial; this does the same thing as the command C-h t (help-with-tutorial). To activate a link, either move point onto it and type RET, or click on it with mouse-1 (the left mouse button).

當 Emacs 啟動時，初始幀顯示一個名為 '*GNU Emacs*'。此啟動畫麵包含有關 Emacs 的資訊以及對初學者有用的常見任務的連結。例如，啟動 'Emacs教程' 連結開啟 Emacs 教學；C-h t這與命令( )的作用相同help-with-tutorial。要啟動鏈接，請將點移到其上並鍵入，或使用（滑鼠左鍵） RET單擊它。mouse-1

Using a command line argument, you can tell Emacs to visit one or more files as soon as it starts up. For example, emacs foo.txt starts Emacs with a buffer displaying the contents of the file ‘foo.txt’. This feature exists mainly for compatibility with other editors, which are designed to be launched from the shell for short editing sessions. If you call Emacs this way, the initial frame is split into two windows—one showing the specified file, and the other showing the startup screen. See Multiple Windows.

使用命令列參數，您可以告訴 Emacs 在啟動時立即存取一個或多個檔案。例如，emacs foo.txt啟動 Emacs，並使用顯示檔案內容的緩衝區 'foo.txt'。此功能的存在主要是為了與其他編輯器相容，這些編輯器旨在從 shell 啟動以進行簡短的編輯會話。如果您以這種方式呼叫 Emacs，初始框架將分為兩個視窗 — 一個顯示指定的文件，另一個顯示啟動畫面。請參閱多個視窗。

Generally, it is unnecessary and wasteful to start Emacs afresh each time you want to edit a file. The recommended way to use Emacs is to start it just once, just after you log in, and do all your editing in the same Emacs session. See File Handling, for information on visiting more than one file. If you use Emacs this way, the Emacs session accumulates valuable context, such as the kill ring, registers, undo history, and mark ring data, which together make editing more convenient. These features are described later in the manual.

一般來說，每次編輯檔案時都重新啟動 Emacs 是不必要的，也是浪費的。使用 Emacs 的建議方法是在登入後僅啟動一次，並在同一個 Emacs 會話中進行所有編輯。有關存取多個文件的信息，請參閱文件處理。如果您以這種方式使用 Emacs，Emacs 會話會累積有價值的上下文，例如終止環、寄存器、撤消歷史記錄和標記環數據，這些一起使編輯更加方便。這些功能將在手冊後面進行描述。

To edit a file from another program while Emacs is running, you can use the emacsclient helper program to open a file in the existing Emacs session. See Using Emacs as a Server.

要在 Emacs 執行時從另一個程式編輯文件，您可以使用emacsclient幫助程式在現有 Emacs 會話中開啟文件。請參閱使用 Emacs 作為伺服器。

Emacs accepts other command line arguments that tell it to load certain Lisp files, where to put the initial frame, and so forth. See Command Line Arguments for Emacs Invocation.

Emacs 接受其他命令列參數，告訴它載入某些 Lisp 檔案、在哪裡放置初始框架等等。請參閱Emacs 呼叫的命令列參數。

If the variable inhibit-startup-screen is non-nil, Emacs does not display the startup screen. In that case, if one or more files were specified on the command line, Emacs simply displays those files; otherwise, it displays a buffer named *scratch*, which can be used to evaluate Emacs Lisp expressions interactively. See Lisp Interaction Buffers. You can set the variable inhibit-startup-screen using the Customize facility (see Easy Customization Interface), or by editing your initialization file (see The Emacs Initialization File).4

如果變數inhibit-startup-screen為非 - nil，Emacs 不會顯示啟動畫面。在這種情況下，如果在命令列上指定了一個或多個文件，Emacs 只會顯示這些文件；否則，它會顯示一個名為*刮痕*，可用於互動式地計算 Emacs Lisp 表達式。請參閱Lisp 交互緩衝區。inhibit-startup-screen您可以使用自訂工具（請參閱輕鬆自訂介面）或透過編輯初始化檔案（請參閱Emacs 初始化檔案）來設定變數 。

You can also force Emacs to display a file or directory at startup by setting the variable initial-buffer-choice to a string naming that file or directory. The value of initial-buffer-choice may also be a function (of no arguments) that should return a buffer which is then displayed. If initial-buffer-choice is non-nil, then if you specify any files on the command line, Emacs still visits them, but does not display them initially.

您也可以透過將變數設定為命名該檔案或目錄的字串來強制 Emacs 在啟動時顯示該檔案或目錄initial-buffer-choice。的值 initial-buffer-choice也可以是一個函數（無參數），它應該會傳回一個隨後顯示的緩衝區。如果initial-buffer-choice是非- nil，那麼如果您在命令列上指定任何文件，Emacs 仍然會存取它們，但最初不會顯示它們。
