#+TITLE: GNU Emacs manual - 8 Basic Editing Commands
#+AUTHOR: Free Software Foundation, Inc.
#+DATE: <2023-09-28 Thu>

* 8.1 Inserting Text
  
You can insert an ordinary graphic character (e.g., ‘a’, ‘B’, ‘3’, and ‘=’) by typing the associated key. This adds the character to the buffer at point. Insertion moves point forward, so that point remains just after the inserted text. See Point.

您可以插入普通圖形字元（例如，'A','乙','3'， 和 '=') 透過鍵入關聯的鍵。這會將字元添加到緩衝區中的點。插入將點向前移動，以便該點保留在插入的文字後面。參見點。

To end a line and start a new one, type RET (newline). (The RET key may be labeled Return, or Enter, or with a funny-looking left-pointing arrow on your keyboard, but we refer to it as RET in this manual.) This command inserts a newline character into the buffer, then indents (see Indentation) according to the major mode. If point is at the end of the line, the effect is to create a new blank line after it and indent the new line; if point is in the middle of a line, the line is split at that position. To turn off the auto-indentation, you can either disable Electric Indent mode (see Convenience Features for Indentation) or type C-j, which inserts just a newline, without any auto-indentation.

若要結束一行並開始新一行，請鍵入RET( newline)。（該鍵可能在鍵盤上RET標記為Return、 或，或 並帶有一個看起來很滑稽的向左箭頭，但我們在本手冊中是這樣稱呼它的。）此命令將換行符插入到緩衝區中，然後縮排（請參閱縮排）根據主要模式。如果 point 位於行尾，則效果是在其後建立新的空白行並縮排新行；如果點位於一條線的中間，則該線在該位置被分割。若要關閉自動縮進，您可以停用電動縮排模式（請參閱縮排的便利功能）或鍵入，這將僅插入換行符，而無需任何自動縮排。 EnterRETC-j

As we explain later in this manual, you can change the way Emacs handles text insertion by turning on minor modes. For instance, the minor mode called Auto Fill mode splits lines automatically when they get too long (see Filling Text). The minor mode called Overwrite mode causes inserted characters to replace (overwrite) existing text, instead of shoving it to the right. See Minor Modes.

正如我們在本手冊後面所解釋的，您可以透過開啟次要模式來變更 Emacs 處理文字插入的方式。例如，稱為自動填滿模式的次要模式會在行太長時自動分割行（請參閱填滿文字）。稱為覆蓋模式的次要模式會導致插入的字元替換（覆蓋）現有文本，而不是將其推到右側。請參閱次要模式。

Only graphic characters can be inserted by typing the associated key; other keys act as editing commands and do not insert themselves. For instance, DEL runs the command delete-backward-char by default (some modes bind it to a different command); it does not insert a literal ‘DEL’ character (ASCII character code 127).

透過鍵入相關鍵只能插入圖形字元；其他按鍵充當編輯命令並且不會自行插入。例如， 預設DEL運行命令（某些模式將其綁定到不同的命令）；delete-backward-char它不會插入文字 '德爾' 字元（ASCII字元代碼 127）。

To insert a non-graphic character, or a character that your keyboard does not support, first quote it by typing C-q (quoted-insert). There are two ways to use C-q:

若要插入非圖形字元或鍵盤不支援的字符，請先鍵入 ( )將其引用。有兩種使用方法： C-qquoted-insertC-q

- C-q followed by any non-graphic character (even C-g) inserts that character. For instance, C-q DEL inserts a literal ‘DEL’ character.

  C-q後面跟著任何非圖形字元（甚至C-g）插入該字元。例如，插入文字 'C-q DEL德爾' 特徵。
  
- C-q followed by a sequence of octal digits inserts the character with the specified octal character code. You can use any number of octal digits; any non-digit terminates the sequence. If the terminating character is RET, that RET serves only to terminate the sequence. Any other non-digit terminates the sequence and then acts as normal input—thus, C-q 1 0 1 B inserts ‘AB’.

  C-q後面跟著八進位數字序列插入具有指定八進位字元代碼的字元。您可以使用任意數量的八進制數字；任何非數字都會終止序列。如果終止字元是RET，則RET僅用於終止序列。任何其他非數字都會終止序列，然後充當正常輸入 - 因此，C-q 1 0 1 B插入 'AB'。

  The use of octal sequences is disabled in ordinary non-binary Overwrite mode, to give you a convenient way to insert a digit instead of overwriting with it.

  在普通非二進制覆蓋模式下禁用八進制序列的使用，以便為您提供一種方便的方法來插入數字而不是用它進行覆蓋。
  
To use decimal or hexadecimal instead of octal, set the variable read-quoted-char-radix to 10 or 16. If the radix is 16, the letters a to f serve as part of a character code, just like digits. Case is ignored.

若要使用十進位或十六進位取代八進位，請將變數設為 read-quoted-char-radix10 或 16。如果基數為 16，則字母a將f用作字元代碼的一部分，就像數字一樣。大小寫被忽略。

A few common Unicode characters can be inserted via a command starting with C-x 8. For example, C-x 8 [ inserts ‘ which is Unicode code-point U+2018 LEFT SINGLE QUOTATION MARK, sometimes called a left single “curved quote” or “curly quote”. Similarly, C-x 8 ], C-x 8 { and C-x 8 } insert the curved quotes ’, “ and ”, respectively. Also, a working Alt key acts like C-x 8 (unless followed by RET); e.g., A-[ acts like C-x 8 [ and inserts ‘. To see which characters have C-x 8 shorthands, type C-x 8 C-h.

可以透過以 開頭的命令插入一些常見的 Unicode 字元C-x 8。例如，C-x 8 [插入‘ Unicode 代碼點 U+2018左單引號，有時稱為左單「彎引號」或「彎引號」。同樣，C-x 8 ]、C-x 8 {和分別C-x 8 }插入彎曲引號’、“和”。此外，工作 Alt鍵的作用類似C-x 8（除非後面跟著RET）；例如，A-[行為類似於C-x 8 [並插入‘。若要查看哪些字元有C-x 8簡寫，請輸入C-x 8 C-h。

Alternatively, you can use the command C-x 8 RET (insert-char). This prompts for the Unicode name or code-point of a character, using the minibuffer. If you enter a name, the command provides completion (see Completion). If you enter a code-point, it should be as a hexadecimal number (the convention for Unicode), or a number with a specified radix, e.g., #o23072 (octal); See Integer Basics in The Emacs Lisp Reference Manual. The command then inserts the corresponding character into the buffer.

或者，您可以使用命令 ( )。這將提示使用迷你緩衝區輸入字元的 Unicode 名稱或代碼點。如果您輸入名稱，指令會提供補全（請參閱補全）。如果輸入代碼點，它應該是十六進位數字（Unicode 的約定），或具有指定基數的數字，例如 （八進位）；請參閱Emacs Lisp 參考手冊中的整數基礎知識。然後該命令將相應的字元插入到緩衝區中。 C-x 8 RETinsert-char#o23072

For example, the following all insert the same character:

例如，以下都插入相同的字元：

#+begin_src bash
C-x 8 RET left single quotation mark RET
C-x 8 RET left sin TAB RET
C-x 8 RET 2018 RET
C-x 8 [
A-[  (if the Alt key works)
`    (in Electric Quote mode)
#+end_src

A numeric argument to C-q or C-x 8 ... specifies how many copies of the character to insert (see Numeric Arguments).

C-q或 的數字參數C-x 8 ...指定要插入的字元的數量（請參閱數字參數）。

As an alternative to C-x 8, you can select the corresponding transient input method by typing C-u C-x \ iso-transl RET, then temporarily activating this transient input method by typing C-x \ [ will insert the same character ‘ (see transient input method).

作為 的替代C-x 8方法，您可以透過鍵入 來選擇對應的瞬時輸入法，然後透過鍵入暫時啟動該瞬時輸入法 將插入相同的字元（請參閱瞬時輸入法）。 C-u C-x \ iso-transl RETC-x \ [‘

In addition, in some contexts, if you type a quotation using grave accent and apostrophe `like this', it is converted to a form ‘like this’ using single quotation marks, even without C-x 8 commands. Similarly, typing a quotation ``like this'' using double grave accent and apostrophe converts it to a form “like this” using double quotation marks. See Quotation Marks.

此外，在某些上下文中，如果您使用重音符號和撇號鍵入引文，即使沒有命令，它也會轉換為使用單引號的`like this'形式 。同樣，使用雙音符號和撇號鍵入引文會將其轉換為使用雙引號的形式。請參閱引號。 ‘like this’C-x 8``like this''“like this”
