#+TITLE: GNU Emacs manual - 3 Keys
#+AUTHOR: Free Software Foundation, Inc.
#+DATE: <2023-09-22 Fri>

* 3 Keys

Some Emacs commands are invoked by just one input event; for example, C-f moves forward one character in the buffer. Other commands take two or more input events to invoke, such as C-x C-f and C-x 4 C-f.

有些 Emacs 指令僅由一個輸入事件呼叫；例如，C-f在緩衝區中向前移動一個字元。其他命令需要兩個或多個輸入事件來調用，例如C-x C-f和C-x 4 C-f。

A key sequence, or key for short, is a sequence of one or more input events that is meaningful as a unit. If a key sequence invokes a command, we call it a complete key; for example, C-f, C-x C-f and C-x 4 C-f are all complete keys. If a key sequence isn’t long enough to invoke a command, we call it a prefix key; from the preceding example, we see that C-x and C-x 4 are prefix keys. Every key sequence is either a complete key or a prefix key.

鍵序列（或簡稱鍵）是作為一個單元有意義的一個或多個輸入事件的序列。如果一個按鍵序列呼叫一個命令，我們稱之為完整按鍵；例如 、 C-f和C-x C-f都是C-x 4 C-f完整的鍵。如果按鍵序列的長度不足以呼叫命令，我們稱之為 前綴鍵；從前面的範例中，我們看到C-x 和C-x 4是前綴鍵。每個鍵序列要么是完整鍵，要么是前綴鍵。

A prefix key combines with the following input event to make a longer key sequence. For example, C-x is a prefix key, so typing C-x alone does not invoke a command; instead, Emacs waits for further input (if you pause for longer than a second, it echoes the C-x key to prompt for that input; see The Echo Area). C-x combines with the next input event to make a two-event key sequence, which could itself be a prefix key (such as C-x 4), or a complete key (such as C-x C-f). There is no limit to the length of key sequences, but in practice they are seldom longer than three or four input events.

前綴鍵與後續輸入事件組合以形成更長的鍵序列。例如，C-x是前綴鍵，因此C-x單獨鍵入不會呼叫命令；相反，Emacs 會等待進一步的輸入（如果您暫停超過一秒，它會回顯按鍵C-x以提示輸入；請參閱回顯區域）。 C-x與下一個輸入事件組合以形成雙事件鍵序列，該序列本身可以是前綴鍵（例如C-x 4），也可以是完整鍵（例如C-x C-f）。鍵序列的長度沒有限制，但實際上它們很少長於三個或四個輸入事件。

You can’t add input events onto a complete key. For example, because C-f is a complete key, the two-event sequence C-f C-k is two key sequences, not one.

您無法將輸入事件新增至完整的按鍵。例如，因為C-f是一個完整的按鍵，所以雙事件序列C-f C-k是兩個按鍵序列，而不是一個。

By default, the prefix keys in Emacs are C-c, C-h, C-x, C-x RET, C-x @, C-x a, C-x n, C-x r, C-x t, C-x v, C-x 4, C-x 5, C-x 6, ESC, and M-g. (F1 and F2 are aliases for C-h and C-x 6.) This list is not cast in stone; if you customize Emacs, you can make new prefix keys. You could even eliminate some of the standard ones, though this is not recommended for most users; for example, if you remove the prefix definition of C-x 4, then C-x 4 C-f becomes an invalid key sequence. See Customizing Key Bindings.

預設情況下，Emacs 中的前綴鍵為C-c, C-h, C-x, , , , , , , , , , , ,和。（和 是和的別名。）這個清單並不是一成不變的；如果您自訂 Emacs，則可以建立新的前綴鍵。您甚至可以消除一些標準的，儘管不建議大多數用戶這樣做；例如，如果刪除 的前綴定義，則變成無效的鍵序列。請參閱自訂鍵綁定。 C-x RETC-x @C-x aC-x nC-x rC-x tC-x vC-x 4C-x 5C-x 6ESCM-gF1F2C-hC-x 6C-x 4C-x 4 C-f

Typing the help character (C-h or F1) after a prefix key displays a list of the commands starting with that prefix. The sole exception to this rule is ESC: ESC C-h is equivalent to C-M-h, which does something else entirely. You can, however, use F1 to display a list of commands starting with ESC.

在前綴鍵後鍵入幫助字元（C-h或F1）會顯示以該前綴開頭的命令清單。此規則的唯一例外是ESC：ESC C-h相當於C-M-h，它完全執行其他操作。但是，您可以使用F1顯示以 開頭的命令清單ESC。
