#+TITLE: GNU Emacs manual - 4 Mouse Input
#+AUTHOR: Free Software Foundation, Inc.
#+DATE: <2023-09-22 Fri>

* 4 Mouse Input

By default, Emacs supports all the normal mouse actions like setting the cursor by clicking on the left mouse button, and selecting an area by dragging the mouse pointer. All mouse actions can be used to bind commands in the same way you bind them to keyboard events (see Keys). This section provides a general overview of using the mouse in Emacs; see Mouse Commands for Editing, and the sections that follow it, for more details about mouse commands in Emacs.

預設情況下，Emacs 支援所有正常的滑鼠操作，例如透過點擊滑鼠左鍵設定遊標，以及透過拖曳滑鼠指標來選擇區域。所有滑鼠操作都可用於綁定命令，就像將它們綁定到鍵盤事件一樣（請參閱按鍵）。本節提供了在 Emacs 中使用滑鼠的總體概述；有關Emacs 中滑鼠命令的更多詳細信息，請參閱用於編輯的滑鼠命令及其後面的部分。

When you click the left mouse button, Emacs receives a mouse-1 event. To see what command is bound to that event, you can type C-h c and then press the left mouse button. Similarly, the middle mouse button is mouse-2 and the right mouse button is mouse-3. If you have a mouse with a wheel, the wheel events are commonly bound to either wheel-down or wheel-up, or mouse-4 and mouse-5, but that depends on the operating system configuration.

當您按一下滑鼠左鍵時，Emacs 會收到一個 mouse-1事件。若要查看與該事件綁定的命令，您可以鍵入C-h c然後按滑鼠左鍵。同樣，滑鼠中鍵為mouse-2，滑鼠右鍵為 mouse-3。如果您的滑鼠帶有滾輪，則滾輪事件通常會綁定到 或wheel-down、wheel-up或 mouse-4和mouse-5，但這取決於作業系統配置。

In general, legacy X systems and terminals (see Using a Mouse in Text Terminals) will report mouse-4 and mouse-5, while all other systems will report wheel-down and wheel-up.

一般來說，舊版 X 系統和終端（請參閱在文字終端中使用滑鼠）將報告mouse-4和mouse-5，而所有其他系統將報告wheel-down和wheel-up。

Some mice also have a horizontal scroll wheel, and touchpads usually support scrolling horizontally as well. These events are reported as wheel-left and wheel-right on all systems other than terminals and legacy X systems, where they are mouse-6 and mouse-7.

有些滑鼠還具有水平滾輪，觸控板通常也支援水平滾動。這些事件在終端和遺留 X 系統之外的所有系統上報告 wheel-left為和 。 wheel-rightmouse-6mouse-7

You can also combine keyboard modifiers with mouse events, so you can bind a special command that triggers when you, for instance, holds down the Meta key and then uses the middle mouse button. In that case, the event name will be M-mouse-2.

您也可以將鍵盤修飾符與滑鼠事件結合起來，這樣您就可以綁定一個特殊的命令，該命令會在您按住 Meta 鍵然後使用滑鼠中鍵時觸發。在這種情況下，事件名稱將為M-mouse-2。

On some systems, you can also bind commands for handling touch screen events. In that case, the events are called touchscreen-update and touchscreen-end.

在某些系統上，您也可以綁定命令來處理觸控螢幕事件。在這種情況下，事件稱為 touchscreen-update和touchscreen-end。
