* 29 Maintaining Large Programs

This chapter describes Emacs features for maintaining medium- to large-size programs and packages. These features include:

- Unified interface to Support for Version Control Systems (VCS) that record the history of changes to source files.
- Commands for handling programming projects.
- A specialized mode for maintaining ChangeLog files that provide a chronological log of program changes.
- Xref, a set of commands for displaying definitions of symbols (a.k.a. “identifiers”) and their references.
- EDE, the Emacs’s own IDE.
- A mode for merging changes to program sources made on separate branches of development.
- A minor-mode for highlighting bug references and visiting the referenced bug reports in their issue tracker.

If you are maintaining a large Lisp program, then in addition to the features described here, you may find the Emacs Lisp Regression Testing (ERT) library useful (see ERT in Emacs Lisp Regression Testing).

- Version Control
- Working with Projects
- Change Logs
- Find Identifier References
- Emacs Development Environment
- Merging Files with Emerge
- Bug Reference
